services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mutualmetrics-backend
    environment:
      - APP_NAME=MutualMetrics Backend
      - APP_VERSION=0.1.0
      - ALLOWED_ORIGINS=http://localhost:5173,http://frontend:5173
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: mutualmetrics-frontend
    ports:
      - "5173:80"
    depends_on:
      backend:
        condition: service_started

networks:
  default:
    name: mutualmetrics

